version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - ./api:/kitty-api/api
      - ./tests:/kitty-api/tests
      - ./tox.ini:/kitty-api/tox.ini
    environment:
      - PORT=8000
    ports:
      - 8000:8000