name: Continuous Integration

on: [push, pull_request]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build web image managed by docker-compose
        run: docker-compose build
      - name: Run test using tox
        run: docker-compose run web tox